### ISSUE TITLE
Support for python 2.7

### ISSUE THREAD

**Issue by paytience** [gramaziokohler/roslibpy#55]
The README says roslibpy is supported for Python 2.7, however dependencies like txaio and autobahn only support Python 3.5+. Does this mean it is no longer supported? I tried installing txaio and autobahn versions that supports Python 2.7, but I get:

:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name verify_ip_address'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.

## Expected Result

Get version number when using *roslibpy --version*, or be able to import roslibpy.

## Actual Result
casper@USERNAME-desktop:~/$ roslibpy --version
Traceback (most recent call last):
  File "/home/USERNAME/.local/bin/roslibpy", line 7, in <module>
    from roslibpy.__main__ import main
  File "/home/USERNAME/.local/lib/python2.7/site-packages/roslibpy/__init__.py", line 95, in <module>
    from .ros import Ros
  File "/home/USERNAME/.local/lib/python2.7/site-packages/roslibpy/ros.py", line 10, in <module>
    from .comm import RosBridgeClientFactory
  File "/home/USERNAME/.local/lib/python2.7/site-packages/roslibpy/comm/__init__.py", line 9, in <module>
    from .comm_autobahn import AutobahnRosBridgeClientFactory as RosBridgeClientFactory
  File "/home/USERNAME/.local/lib/python2.7/site-packages/roslibpy/comm/comm_autobahn.py", line 6, in <module>
    from autobahn.twisted.websocket import WebSocketClientFactory
  File "/home/USERNAME/.local/lib/python2.7/site-packages/autobahn/twisted/__init__.py", line 37, in <module>
    from autobahn.twisted.choosereactor import install_reactor
  File "/home/USERNAME/.local/lib/python2.7/site-packages/autobahn/twisted/choosereactor.py", line 30, in <module>
    import txaio
  File "/home/USERNAME/.local/lib/python2.7/site-packages/txaio/__init__.py", line 29, in <module>
    from txaio.interfaces import IFailedFuture, ILogger
  File "/home/USERNAME/.local/lib/python2.7/site-packages/txaio/interfaces.py", line 41, in <module>
    class IBatchedTimer(abc.ABC):
AttributeError: 'module' object has no attribute 'ABC'

## Reproduction Steps
```python
import roslibpy

```

## System Information
Python 2.7, Ubuntu 16.04, ROS Kinetic.

**Comment by gonzalocasas** [comment]
Travis build is always built on python 2.7 as well so it most definitely work there. You need to install a version of twisted/autobahn that still supported python 2.7 of course, I believe the latest to support 2.x are versions 19.x.

**Comment by gonzalocasas** [comment]
If you are having issues with the installation, try miniconda/anaconda installs, they might simplify the dep resolution.

**Comment by paytience** [comment]
Okay thank you, I think the problem was the installation order, autobahn before txaio did the trick. Thanks for the help
