### ISSUE TITLE
Error when launching rosbridge_websocket

### ISSUE THREAD

**Issue by philianeles** [gramaziokohler/roslibpy#58]
Summary.
`$ roslaunch rosbridge_server rosbridge_websocket.launch`

## Expected Result
rosbridge_websocket launches correctly 

## Actual Result
Getting the error message:

> $ roslaunch rosbridge_server rosbridge_websocket.launch
> ... logging to /home/sercan/.ros/log/10b77bf4-7c00-11ea-b8aa-54e1ad9244b0/roslaunch-ITA-GRAM-W-60-24875.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://ITA-GRAM-W-60:49861/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosapi/params_glob: [*]
>  * /rosapi/services_glob: [*]
>  * /rosapi/topics_glob: [*]
>  * /rosbridge_websocket/address:
>  * /rosbridge_websocket/authenticate: False
>  * /rosbridge_websocket/bson_only_mode: False
>  * /rosbridge_websocket/delay_between_messages: 0
>  * /rosbridge_websocket/fragment_timeout: 600
>  * /rosbridge_websocket/max_message_size: None
>  * /rosbridge_websocket/params_glob: [*]
>  * /rosbridge_websocket/port: 9090
>  * /rosbridge_websocket/retry_startup_delay: 5
>  * /rosbridge_websocket/services_glob: [*]
>  * /rosbridge_websocket/topics_glob: [*]
>  * /rosbridge_websocket/unregister_timeout: 10
>  * /rosbridge_websocket/use_compression: False
>  * /rosdistro: melodic
>  * /rosversion: 1.14.3
> 
> NODES
>   /
>     rosapi (rosapi/rosapi_node)
>     rosbridge_websocket (rosbridge_server/rosbridge_websocket)
> 
> auto-starting new master
> process[master]: started with pid [24885]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 10b77bf4-7c00-11ea-b8aa-54e1ad9244b0
> process[rosout-1]: started with pid [24896]
> started core service [/rosout]
> process[rosbridge_websocket-2]: started with pid [24903]
> process[rosapi-3]: started with pid [24904]
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/rosbridge_server/rosbridge_websocket", line 35, in <module>
>     import rospy
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
>     from .client import spin, myargv, init_node, \
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 60, in <module>
>     import rospy.impl.init
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/init.py", line 58, in <module>
>     from rosgraph.rosenv import DEFAULT_MASTER_PORT  # default port for master's to bind to
> ImportError: cannot import name DEFAULT_MASTER_PORT
> Traceback (most recent call last):
>   File "/opt/ros/melodic/lib/rosapi/rosapi_node", line 34, in <module>
>     import rospy
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/__init__.py", line 49, in <module>
>     from .client import spin, myargv, init_node, \
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 60, in <module>
>     import rospy.impl.init
>   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/init.py", line 58, in <module>
>     from rosgraph.rosenv import DEFAULT_MASTER_PORT  # default port for master's to bind to
> ImportError: cannot import name DEFAULT_MASTER_PORT
> [rosbridge_websocket-2] process has died [pid 24903, exit code 1, cmd /opt/ros/melodic/lib/rosbridge_server/rosbridge_websocket __name:=rosbridge_websocket __log:=/home/sercan/.ros/log/10b77bf4-7c00-11ea-b8aa-54e1ad9244b0/rosbridge_websocket-2.log].
> log file: /home/sercan/.ros/log/10b77bf4-7c00-11ea-b8aa-54e1ad9244b0/rosbridge_websocket-2*.log
> [rosapi-3] process has died [pid 24904, exit code 1, cmd /opt/ros/melodic/lib/rosapi/rosapi_node __name:=rosapi __log:=/home/sercan/.ros/log/10b77bf4-7c00-11ea-b8aa-54e1ad9244b0/rosapi-3.log].
> log file: /home/sercan/.ros/log/10b77bf4-7c00-11ea-b8aa-54e1ad9244b0/rosapi-3*.log

## System Information
WSL, rosdistro: melodic, rosversion: 1.14.3

What could be the reason that it throws the import error:
`ImportError: cannot import name DEFAULT_MASTER_PORT`
?

**Comment by philianeles** [comment]
Ok after running `sudo apt-get update` and `sudo apt-get upgrade` it seems to work! 
I think some stuff were mixed up in ros installation but I works now.
